apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{.Values.pg.teamId}}-{{.Values.pg.name}}"  
  namespace: {{.Values.pg.namespace}} 
spec:
  rules:
    - host: {{.Values.pg.name}}.{{.Values.pg.teamId}}.{{.Values.global.domain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                  name: {{.Values.pg.teamId}}-{{.Values.pg.name}}
                  port:
                    number: {{.Values.pg.port}}
          - path: /master/metrics
            pathType: Prefix
            backend:
              service:
                  name: {{.Values.pg.teamId}}-{{.Values.pg.name}}-svc-metrics-master
                  port:
                    number: {{.Values.pg.metricPort}}    
          - path: /replica/metrics
            pathType: Prefix
            backend:
              service:
                  name: {{.Values.pg.teamId}}-{{.Values.pg.name}}-svc-metrics-replica
                  port:
                    number: {{.Values.pg.metricPort}}                                       
