global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: msteam
  group_by:
  - alertname
  - cluster
  - service
  - app_group
  routes:
  - receiver: msteam
    match:
      app_group: msteam
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 1h
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - cluster
  - service
  - app_group
receivers:
- name: msteam
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://localhost:2000/msteam
    max_alerts: 0
templates: []
