global:
  scrape_interval: 5m
  scrape_timeout: 2m
  evaluation_interval: 15s
  external_labels:
    myenv: naren
    mygroup: monitoring
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets:
      - localhost:9093
rule_files:
- /etc/prometheus/alerts/*.yml
scrape_configs:
- job_name: Prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    labels:
      app: Prometheus
- job_name: Prometheus-node
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9100
    labels:
      app: NodeExporter
- job_name: blackbox
  honor_timestamps: true
  params:
    module:
    - http_2xx
  scrape_interval: 5m
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  basic_auth:
    username: daaas
    password: <secret>
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: localhost:9115
    action: replace
  static_configs:
  - targets:
    - https://twitter.com/
remote_write:
- url: http://localhost:8480/insert/0/prometheus/
  remote_timeout: 30s
  queue_config:
    capacity: 2500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
