kind: Pod
apiVersion: v1
metadata:
  name: demo
  labels:
    app: demo
spec:
  containers:
  - name: demo
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=demo"
---
kind: Service
apiVersion: v1
metadata:
  name: demo
spec:
  selector:
    app: demo
  ports:
  - port: 5678 

