kind: Pod
apiVersion: v1
metadata:
  name: demo
  labels:
    app: demo
spec:
  containers:
  - name: demo
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=demo"
---
kind: Service
apiVersion: v1
metadata:
  name: demo
spec:
  selector:
    app: demo
  ports:
  - port: 5678 

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  rules:
  - host: demo.haproxy.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: demo
            port:
              number: 5678
  tls:
  - hosts:
      - demo.naren4biz.in
    secretName: demo-tls              

